# Generated by Django 4.0.6 on 2022-08-15 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_author_slug_alter_author_excerpt_alter_type_excerpt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geotag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField()),
                ('json', models.JSONField()),
            ],
        ),
        migrations.RemoveField(
            model_name='content',
            name='geotag_json',
        ),
        migrations.RemoveField(
            model_name='content',
            name='geotag_title',
        ),
        migrations.AddField(
            model_name='content',
            name='geotags',
            field=models.ManyToManyField(to='contents.geotag'),
        ),
    ]
