# Generated by Django 4.0.6 on 2022-08-15 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0004_geotag_remove_content_geotag_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='geotag',
            name='amar_code',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
