# Generated by Django 4.0.6 on 2022-08-16 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0005_geotag_amar_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geotag',
            name='amar_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
