# Generated by Django 4.0.6 on 2022-08-18 05:34

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0007_content_translators_alter_content_authors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='img',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='pdf_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
