# Generated by Django 4.0.6 on 2022-08-21 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0008_alter_content_img_alter_content_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='publication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contents.publication'),
        ),
    ]
