# Generated by Django 4.0.6 on 2022-08-21 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0009_alter_content_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='pub_date_full',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
