# Generated by Django 4.0.6 on 2022-08-22 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0010_content_pub_date_full'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='pub_date_m',
            field=models.IntegerField(blank=True, choices=[(1, 'فروردین'), (2, 'اردیبهشت'), (3, 'خرداد'), (4, 'تیر'), (5, 'مرداد'), (6, 'شهریور'), (7, 'مهر'), (8, 'آبان'), (9, 'آذر'), (10, 'دی'), (11, 'بهمن'), (12, 'اسفند')], null=True),
        ),
    ]
